### ISSUE TITLE
Exposed password problem

### ISSUE THREAD

**Issue by edpichler** [h-thurow/Simple-JNDI#12]
How is the best way to hide password from datasource.properties file when using simple-jndi? Is there a way to use environment variables?

**Comment by h-thurow** [comment]
edpichler also wrote:

"How can I activate variable interpolation of Apache Commons Configuration?
I saw it [is possible on your JUnit tests](https://github.com/h-thurow/Simple-JNDI/blob/master/src/test/java/commons/configuration/JNDIConfigurationTest.java#L298):
...
By the way, the reason I need to use it is to hide passwords on property files. I will use environment variables."

Hello Eduardo,

interpolation is done by JndiConfiguration. So such variables will not be interpolated by calling InitialContext.lookup(). Instead you have to pass the InitialContext to a JndiConfiguration instance: 

	InitialContext ctx = new InitialContext();
	final JNDIConfiguration jndiConf = new JNDIConfiguration(ctx);

Then use one of JNDIConfiguration's getter methods, to access the interpolated values, e. g.:

	jndiConf.getString("...")

It is important to correctly adjust org.osjava.sj.delimiter and jndi.syntax.separator as demonstrated by the unit tests in JNDIConfigurationTest class.

regards
Holger

**Comment by edpichler** [comment]
Oh, now I got it Mr @h-thurow, thank you.

In the case, I am using [weld-junit5](https://github.com/weld/weld-junit/blob/master/junit5/README.md#weldjunit5autoextension), I don't know if it's possible without changing the weld-junit source code.

@h-thurow is there a way where I can, after reading the properties file, replace the values in runtime using Environment Variables?

**Comment by h-thurow** [comment]
Try this. Use an arbitrary password in your datasource.properties file. Before the first connection is made, lookup the DataSource in your application, cast it to org.apache.commons.dbcp2.BasicDataSource and set the correct password by calling BasicDataSource#setPassword.

**Comment by edpichler** [comment]
@h-thurow wow, it's worked. Thank you Mr. Hackerman!

Maybe, hiding passwords would be nice this feature, but I don't know if this is a role of this project or it is a charge of weld-junit. 
By the way, I just remember that on weld-junit I can create a custom resource and attach it to the JNDI context. I realized that I am using simple-JNDI attracted by the simplicity of the project, and due this problem, I am not sure if I will keep this dependency.
