### ISSUE TITLE
How to setup a transaction manager?

### ISSUE THREAD

**Issue by edpichler** [h-thurow/Simple-JNDI#13]
Hello, is it possible to configure a transaction manager to be accessible by JNDI?
I tried this, but didn't work, once each time InitialContext is created, it reads from the properties files and replace all previously binded resources:

```
            InitialContext jndiCtx = new InitialContext();
            jndiCtx.bind(JNDI_TRANSACTION_MANAGER, createTransactionManager());
            jndiCtx.bind(JNDI_DATASOURCE_NAME, createDataSource());
```
Do you have any idea no I can have my `TransactionManager` binded too?

**Comment by edpichler** [comment]
I debugged Hibernate and discovered that he calls the context.close(). 
Using the flag `org.osjava.sj.jndi.ignoreClose=true` apparently solves my problem.
I am glad all of this is open source, so I could debug it all to understand how it works.

**Comment by h-thurow** [comment]
Thanks for your feedback
