### ISSUE TITLE
Invalid subcontext 'java:comp' in context ''

### ISSUE THREAD

**Issue by kolbma** [h-thurow/Simple-JNDI#14]
Hi,

what is wrong here?

A manual lookup in the unit test works. But when EclipseLink tries to lookup there is this exception...

```
Apr 27, 2019 12:14:53 AM org.osjava.sj.jndi.MemoryContext lookup
SEVERE: AbstractContext#lookup("java:comp/env/jdbc/MSDataDS"): Invalid subcontext 'java:comp' in context '': 
AbstractContext{namesToObjects={}, 
subContexts={java:comp=AbstractContext{namesToObjects={}, 
subContexts={env=AbstractContext{namesToObjects={}, 
subContexts={jdbc=AbstractContext{namesToObjects={MSDataDS=org.h2.jdbcx.JdbcDataSource::::jdbc:h2:file:./target/msdata;AUTO_SERVER=TRUE::::sa}, 
subContexts={}, 
env={
org.osjava.sj.jndi.shared=true, 
org.osjava.sj.root=src/test/jndi/, 
java.naming.factory.initial=org.osjava.sj.MemoryContextFactory, 
org.osjava.sj.delimiter=/, 
jndi.syntax.separator=/, 
jndi.syntax.direction=left_to_right, 
org.osjava.sj.space=java:comp/env, 
org.osjava.sj.factory=org.osjava.sj.MemoryContextFactory}, nameParser=org.osjava.sj.jndi.SimpleNameParser@1849db1a, 
nameInNamespace=java:comp/env/jdbc, 
nameLock=true}}, 
env={
org.osjava.sj.jndi.shared=true, 
org.osjava.sj.root=src/test/jndi/, 
java.naming.factory.initial=org.osjava.sj.MemoryContextFactory, 
org.osjava.sj.delimiter=/, 
jndi.syntax.separator=/, 
jndi.syntax.direction=left_to_right, 
org.osjava.sj.space=java:comp/env, 
org.osjava.sj.factory=org.osjava.sj.MemoryContextFactory}, nameParser=org.osjava.sj.jndi.SimpleNameParser@69c79f09, 
nameInNamespace=java:comp/env, 
nameLock=true}}, 
env={
org.osjava.sj.jndi.shared=true, 
org.osjava.sj.root=src/test/jndi/, 
java.naming.factory.initial=org.osjava.sj.MemoryContextFactory, 
org.osjava.sj.delimiter=/, 
jndi.syntax.separator=/, 
jndi.syntax.direction=left_to_right, 
org.osjava.sj.space=java:comp/env, 
org.osjava.sj.factory=org.osjava.sj.MemoryContextFactory}, nameParser=org.osjava.sj.jndi.SimpleNameParser@1ca25c47, 
nameInNamespace=java:comp, 
nameLock=true}}, 
env={
java.naming.factory.initial=org.osjava.sj.MemoryContextFactory, 
org.osjava.sj.delimiter=/, 
jndi.syntax.direction=left_to_right, 
org.osjava.sj.jndi.ignoreClose=false, 
org.osjava.sj.space=java:comp/env, 
org.osjava.sj.root=src/test/jndi/, 
org.osjava.sj.factory=org.osjava.sj.MemoryContextFactory, 
jndi.syntax.separator=/, 
org.osjava.sj.jndi.shared=true}, 
nameParser=org.osjava.sj.jndi.SimpleNameParser@5fcacc0, 
nameInNamespace=, 
nameLock=false}
[EL Severe]: 2019-04-27 00:14:53.576--ServerSession(1523084197)--Exception [EclipseLink-7060] (Eclipse Persistence Services - 2.7.4.v20190115-ad5b7c6b2a): org.eclipse.persistence.exceptions.ValidationException
Exception Description: Cannot acquire data source [java:comp/env/jdbc/MSDataDS].
Internal Exception: javax.naming.NamingException
```

**Comment by h-thurow** [comment]
I do not know EclipseLink, but this is some kind of weird, because the context does exist:
<pre>
SEVERE: AbstractContext#lookup("java:comp/env/jdbc/MSDataDS"): Invalid subcontext 'java:comp' in context '':
AbstractContext{
	namesToObjects={},
	subContexts={
		java:comp=AbstractContext{
			namesToObjects={},
			subContexts={
				env=AbstractContext{
					namesToObjects={},
					subContexts={
						jdbc=AbstractContext{
							namesToObjects={
							MSDataDS=org.h2.jdbcx.JdbcDataSource::::jdbc:h2:file:./target/msdata;AUTO_SERVER=TRUE::::sa},</pre>
It should work with EclipseLink too. There is a post of someone running SimpleJNDI together with EclipseLink. See [Simple-JNDI alongside Tomcat 8](https://github.com/h-thurow/Simple-JNDI/issues/3).

Could you provide some more information?

**Comment by h-thurow** [comment]
Also try to update to the current version. It looks like you are using a version < 0.16.0.

**Comment by kolbma** [comment]
No, this is simple-jndi-0.18.1.

**Comment by kolbma** [comment]
And what information do you need?

Could it be a classloader problem? The EntityManagerFactory and the EntityManager are instances in DAOs of the web application context.
I'm testing static DAO-methods.

But Simple-JNDI logs this lookup, so EclipseLink seems to do the lookup in the correct JNDI implementation.

Does `Invalid subcontext 'java:comp'` mean, that there is a lookup for `java:comp` by EclipseLink? Or is this just the information that the problem is already at `comp`?

**Comment by h-thurow** [comment]
> No, this is simple-jndi-0.18.1.

Maybe there are two different SimpleJNDI versions on your classpath?. There is no org.osjava.sj.jndi.AbstractContext class anymore. It was removed from 0.16.0 on.

**Comment by h-thurow** [comment]
> Does `Invalid subcontext 'java:comp'` mean, that there is a lookup for `java:comp` by EclipseLink? Or is this just the information that the problem is already at `comp`?

Every Context holds references to its subcontexts in a Map ("subContexts"). Here

`subContexts.containsKey('java:comp')`

does not find the context. But as you can see in the serialized context there is a context named 'java:comp'. It looks like there is any difference between the stored key 'java:comp' and 'java:comp' as looked up. You could set a breakpoint in org.osjava.sj.jndi.MemoryContext#lookup(javax.naming.Name) at line 143 to inspect the problem.

**Comment by h-thurow** [comment]
Have you found the cause?

**Comment by wipu** [comment]
I also stumbled upon this problem, so it seems the ticket has been prematurely closed. Since simple-jndi is an overkill for me anyway (I only need a DataSource for eclipselink, no fancy directories etc), I just created a very simple in-memory implementation myself.

**Comment by h-thurow** [comment]
Thanks for your hint. Fixed.
BTW You do not need file system files. Set 

`java.naming.factory.initial = org.osjava.sj.MemoryContextFactory`

in jndi.properties and you will get an empty InitialContext.
Another way is described here: [Programmatically create your contexts and context objects (no resource files needed)](https://github.com/h-thurow/Simple-JNDI/wiki/Programmatically-create-your-contexts-and-context-objects-(no-resource-files-needed))
