### ISSUE TITLE
Handling multiple subcontexts

### ISSUE THREAD

**Issue by Zerrossetto** [h-thurow/Simple-JNDI#15]
Hi,
due to constraints of my application I need to access resources that are both on a java:app and java:comp subcontext. I can't seem to find, on the other hand, hints on the documentation to bind multiple contexts or to to create an aliased context.

Do you know if it's possible?

**Comment by Zerrossetto** [comment]
An update on this topic: what I found is that the property `org.osjava.sj.space` actually gets separated by the delimiter OR the jndi separator, but this leads to nested root contexts (e.g. java:app/java:comp leads to a java:app root context containing a java:comp context), which is not what I expect to happen here.

**Comment by h-thurow** [comment]
SimpleJNDI can not do this for you. You have to reference the java:comp context under java:app programmatically:

```
InitialContext initialContext = new InitialContext();
initialContext.bind("java:app", initialContext.lookup("java:comp"));
```
Do this in some kind of initialization process of your application.

Now an NullPointerException is thrown when initialContext.close() is called. To circumvent this initialize SimpleJNDI with

`org.osjava.sj.jndi.ignoreClose = true`

To really close the context see [Context.close() and Context.destroySubcontext()](https://github.com/h-thurow/Simple-JNDI#contextclose-and-contextdestroysubcontext).
