### ISSUE TITLE
Enhancement request: system property substitution in resource files

### ISSUE THREAD

**Issue by giamma** [h-thurow/Simple-JNDI#17]
When defining a datasource in a property file, or possibly any other supported resource, it would be great to be able to use system property substitution, e.g.

`dataSource.serverName=${database.name}`

This could be especially convenient for docker images or for quickly relocating the database server or also for passwords, which could be exported in the environment rather than being written in the file.

**Comment by h-thurow** [comment]
See [JNDIConfigurationTest#dotDelimitedSharedAndVariableInterpolation()](https://github.com/h-thurow/Simple-JNDI/blob/553ff6ecc93d540a1e70b03334d6e6ef31e4f31c/src/test/java/commons/configuration/JNDIConfigurationTest.java#L177-L204)

**Comment by h-thurow** [comment]
Okay, I see. My last comment is not helpful when defining a datasource, because datasource properties are not read with JNDIConfiguration.

**Comment by h-thurow** [comment]
From just released 0.19.0 on values can reference system properties. To be interpolated they must be in the form

`${sj.sys:name_of_system_property}`

See [SJPropertiesSubstitutionTest](https://github.com/h-thurow/Simple-JNDI/blob/c08a4dc06bdd3a7f94997469528dce6f2397bd5e/src/test/java/org/osjava/sj/loader/SJPropertiesSubstitutionTest.java#L13).
