### ISSUE TITLE
Enhancement: add OSGi metadata

### ISSUE THREAD

**Issue by giamma** [h-thurow/Simple-JNDI#19]
It would be great if the Simple JNDI jar included OSGi metadata.

**Comment by h-thurow** [comment]
A little busy at the moment. Will revise your issues within the next days. Thanks for OSGi support! I have not really an idea of OSGi.

**Comment by giamma** [comment]
I updated the pull request, I found a way to perform the OSGi test as the last one, via two executions of the Surefire Maven plug-in.

**Comment by giamma** [comment]
Thank you so much

**Comment by h-thurow** [comment]
0.20.0 released. Should be available on maven repo soon. Please close this issue when you can confirm everything is working.

**Comment by h-thurow** [comment]
Thanks for your work!
