### ISSUE TITLE
Add JndiLoader.SIMPLE_COLON_REPLACE to overwriteEnvironmentWithSystemProperties

### ISSUE THREAD

**Issue by mike-smey** [h-thurow/Simple-JNDI#2]
Can you please add JndiLoader.SIMPLE_COLON_REPLACE to overwriteEnvironmentWithSystemProperties.
Maybe other props as well?

Thanks and Regards,
Mike

**Comment by h-thurow** [comment]
When I release a new version I will support this too. Until then please use org.osjava.sj.space. It already gets overridden by the system property and is the recommended way to work with ENC.

**Comment by mike-smey** [comment]
Thanks, other suggestions for new rel: support of DBCP2 and new FactoryConverter that would invoke on javax.naming.spi.ObjectFactory objects getObjectInstance method

**Comment by h-thurow** [comment]
Today I released 0.14.0. System properties should now overwrite properties set elsewhere. 

Also new:
https://github.com/h-thurow/Simple-JNDI/wiki/A-more-elegant-way-to-lookup-typed-properties-(New-in-0.14.0)
https://github.com/h-thurow/Simple-JNDI/wiki/Use-slash-separated-lookup-pathes-with-dot-separated-property-names-(New-in-0.14.0)

**Comment by h-thurow** [comment]
Hi Mike,

ObjectFactory Implementations are now supported. In jndi.properties set

    java.naming.factory.object = your.objectfactories.FirstObjectFactory:your.objectfactories.SecondObjectFactory

See https://github.com/h-thurow/Simple-JNDI/blob/master/src/test/java/spi/objectfactories/DemoBeanFactory.java for an ObjectFactory example implementation.

For DBCP 2 and Commons Pool 2 support see https://github.com/h-thurow/Simple-JNDI/wiki/DBCP-2-and-Commons-Pool-2-support-(New-in-0.15.0) .

Best regards
Holger
