### ISSUE TITLE
Example for Programatic creating datasource with dbcp

### ISSUE THREAD

**Issue by AnishJoseph** [h-thurow/Simple-JNDI#22]
This is not an issue just a bit of help. 
I have a need where i need to create a JNDI datasource dynamically and your project seemed ideal for me. However I think i got a bit confused and am unable to proceed.

It would be great if you could you give an example of programatically creating a context object for datasource lookup - say for DBCP2. 
This should be accessed something like java:comp/env/jdbc/example_JNDI_DS  

Thanks a ton in advance,

**Comment by h-thurow** [comment]
I did not test it, so perhaps faulty:
```
Properties properties = new Properties();
properties.setProperty("application.ds.TestDS.type", "javax.sql.DataSource");
properties.setProperty("application.ds.TestDS.driverClassName", "org.gjt.mm.mysql.Driver");
properties.setProperty("application.ds.TestDS.url", "jdbc:mysql://localhost/testdb");
properties.setProperty("application.ds.TestDS.username", "user_name");
properties.setProperty("application.ds.TestDS.password", "password");

InitialContext ctxt = new InitialContext();
JndiLoader loader = new JndiLoader(ctx.getEnvironment());
loader.load(properties, ctx);

DataSource ds = (DataSource) ctxt.lookup("application/ds/TestDS");
```
In jndi.properties:
```
java.naming.factory.object = org.apache.commons.dbcp2.BasicDataSourceFactory
org.osjava.sj.delimiter = .
jndi.syntax.separator = /
```
The example is based on https://github.com/h-thurow/Simple-JNDI/wiki/DataSource-Configuration-DBCP-2-and-Commons-Pool-2-(New-in-0.15.0) and https://github.com/h-thurow/Simple-JNDI/wiki/Programmatically-create-your-contexts-and-context-objects-(no-resource-files-needed).

**Comment by AnishJoseph** [comment]
Thanks a ton h-thurow. I will try it out. 
Just to validate my use case - it will be used in a webapp running on tomcat. Till now i would add a JNDI DS in context.xml and a 3rd party library would use it to access the DS. 
I am now trying to dynamically add a JNDI DS using your simple-jndi - so i would not add the JNDI DS via context.xml - instead i would programatically  create these JNDI datasources. The 3rd party libray i assume will still be able to access the JNDI DS as usual .

**Comment by h-thurow** [comment]
I do not think this example will work in a Tomcat environment, because `ctx.getEnvironment()` will not return a suitable environment for Simple-JNDI. You have to configure a suitable one on your own. See https://github.com/h-thurow/Simple-JNDI/blob/b150fd52b0e5c935e766b19ca112599a6cec53ae/src/test/java/org/osjava/sj/memory/JndiLoader2Test.java#L95

**Comment by AnishJoseph** [comment]
Thanks for the prompt reply. You right, it wont work straightaway - also i am trying to create the JNDI like 'java:comp/env/jdbc/TestDS' - this however throws javax.naming.OperationNotSupportedException: Context is read only

So it works with other names - java:comp does not work for me.

Anyways, i have an option of passing a DS directly to that 3rd party lib (instead of JNDI) - I will check that option out first - if that works I dont need to dynamically create the JNDI datasources.
Thanks once again for all you help and propmt replies

**Comment by h-thurow** [comment]
java:comp is read only. see https://stackoverflow.com/questions/13734391/bind-jndi-datasource-in-tomcat/44783538#44783538

**Comment by AnishJoseph** [comment]
Yes thanks. I had forgotten about that. I have to find a different way now.

**Comment by h-thurow** [comment]
Requires the library really the "java:comp/env" ENC? Or is the lookup path customizable? The java:comp/env" ENC is Tomcat specific.

**Comment by AnishJoseph** [comment]
Oh - i did not know that java:comp/env was Tomcat specific. This hopefully gives an opening - will check if the lookup path is customizable. Thanks a ton

**Comment by h-thurow** [comment]
Sorry, after some googling I think I am wrong
