### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by whytox** [h-thurow/Simple-JNDI#36]
Simple-JNDI is writing **a lot** of debug level logs during the test of my application, is there a way to disable logging?

Thank you for your work.

**Comment by MartaCaffagnini** [comment]
I have the same problem too. I've noticed that the debug logs are filling up the log files, making it challenging to identify other issues.

**Comment by whytox** [comment]
Hi @MartaCaffagnini 

since I couldn't stand a girl looking for help, I dove into the rabbit hole.
and I possibly found a solution for logback on top of spring-boot.

Adding  `-Dlogging.level.org.osjava.sj=OFF` to your VM arguments will disable the logging for the entire Simple-JNDI package.
If that's not what you want, you can even customize the level for each class.
Take a look at [this](https://stackoverflow.com/questions/30571319/spring-boot-logging-pattern/71403675#71403675) for additional explanation.

Let me know if it works for you.

Kind regards,
whytox

**Comment by h-thurow** [comment]
Thanks for your answer @MartaCaffagnini !

**Comment by whytox** [comment]
Thanks @h-thurow 
The official documentation is definitely a better source!
