### ISSUE TITLE
'#' as a value of a property

### ISSUE THREAD

**Issue by himanshushekhar002** [h-thurow/Simple-JNDI#4]
If '#' is there as a property value as (in my case it was in a password for Database connection), then it is misunderstood as a start of the comment and getting escaped by the 'CustomProperties parser' of the library.
How to handle this ?

**Comment by h-thurow** [comment]
I will consider this case in the next SimpleJNDI version. Until then I hope you can circumvent this situation by using a different password.

**Comment by h-thurow** [comment]
I released 0.15.0 with standard compatible support of property file syntax as described at https://en.wikipedia.org/wiki/.properties . Please test it and close the ticket, when it is working now.

**Comment by himanshushekhar002** [comment]
Thanks !!!
