### ISSUE TITLE
Support common property names for SJDataSource

### ISSUE THREAD

**Issue by vectro** [h-thurow/Simple-JNDI#8]
Simple-JNDI expects a parameter called "driver", but many other JNDI implementations, including TomCat, use driverClassName. Simple-JNDI should support that too, in order to allow drop-in of properties files.

**Comment by vectro** [comment]
Besides supporting "driverClassName" in addition to "driver", should also support "username" in addition to "user".

**Comment by h-thurow** [comment]
With DBCP 2 this is done. See https://github.com/h-thurow/Simple-JNDI/wiki/DataSource-Configuration-DBCP-2-and-Commons-Pool-2-(New-in-0.15.0)

**Comment by vectro** [comment]
Neato!
