### ISSUE TITLE
Search classpath for properties files

### ISSUE THREAD

**Issue by vectro** [h-thurow/Simple-JNDI#9]
In addition to searching a specific path on the filesystem, there should be a way to tell Simple-JNDI to search the classpath. That way configuration files can be dropped into the resources folder and Simple-JNDI can find them, no matter where they might be (e.g., in a JAR).

**Comment by bmhm** [comment]
Hi,

you can use this snippet in pom.xml:

```xml
    <testResources>
      <testResource>
        <filtering>true</filtering>
        <directory>src/test/resources</directory>
      </testResource>
    </testResources>
```

and then put into your jndi.properties:

`org.osjava.sj.root=${project.build.testOutputDirectory}/jndi/`

**Comment by derari** [comment]
@bmhm this doesn't help anything when the configuration is distribute in a jar file

**Comment by bmhm** [comment]
@derari what you say is true, but it will help to search the classpath for local tests.

Haven't looked at the source code, but maybe it will suffice to enter a JAR URL or something?

**Comment by derari** [comment]
@bmhm The code just takes the value from the `.properties` and looks for files. The JAR URL thing could work, but you'd need to know the file path and name of the jar at packaging time.

**Comment by h-thurow** [comment]
[From 0.18.0 on you can load files or directories from JARs on classpath.](https://github.com/h-thurow/Simple-JNDI#setting-up-simple-jndi)

**Comment by mauromol** [comment]
Hello, this is still problematic. Why not supporting something like Spring classpath:/ prefix?

I mean, if I'm executing unit tests locally and I want to bundle my property files with my tests, they will be in the classpath, for instance in `jndi` or `com.bla.bla` package. But if my tests are then executed on a Jenkins pipeline with Maven, that package will not be on the same physical file system path and may even be in a JAR (or may not, it depends on how tests are executed, if from the exploded classpath or from the JAR).
So, I would need a mechanism that simply says "hey, my property files are on my classpath at com/bla/bla position". Internally, those resources could be loaded with `Class.getResource()` or `ClassLoader.getResource()`.
Is it possible?
